spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://${DB_HOST_URL}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: never
server:
  port: 8080